function bhai()
{
    document.write(  " TELL HAM = hm2917"     )
document.write( "<br>")
document.write( "  Addition = " +(120+120)  )
document.write( "<br>")
document.write( "Subtraction = "+(120-120) )
document.write( "<br>")
document.write( "Multiplication = " +(120*120 ))
document.write( "<br>")
document.write( "Divite = "+(120/120))

var bilal 
for( bilal=1 ; bilal <=12 ; bilal++)
{ 
    document. write ( bilal+" hello brother you are fine " + '<br><hr>' )
}

}
